name: A workflow from a branch
on: [pull_request, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by event ${{ github.event_name }}"
      - run: echo "Triggered by actor ${{ github.actor }}"
